server:
  port: 9010 #configurar numero de puerto
  tomcat:
    uri-encoding: UTF-8
       
spring:
  datasource:
    url: jdbc:mysql://wagerdy8wddbtest.db.10711341.hostedresource.com:3306/wagerdy8wddbtest
    #username: roger
    #password: empresa
    username: wagerdy8wddbtest
    password: C9cf25!0cc2bf
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #comprueba con cada restart del server si los modelos corresponden con las tablas, si no, hace el update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy # dialectos para la consulta
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect 
        
        
  http:
    encoding:
      charset: UTF-8