server:
  port: 3351 #configurar numero de puerto
   
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wddbtest
    username: roger
    password: empresa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #comprueba con cada restart del server si los modelos corresponden con las tablas, si no, hace el update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy # dialectos para la consulta
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect 